"""create table customer

Revision ID: c9e7d240f360
Revises: 098aa20f9f6e
Create Date: 2020-02-17 22:22:01.850039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e7d240f360'
down_revision = '098aa20f9f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('CustomerId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerName', sa.String(length=255), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('UserAccountId', sa.Integer(), nullable=True),
    sa.Column('PaymentAccount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
