"""initial database migration

Revision ID: efd35b86b916
Revises: 
Create Date: 2020-02-17 21:04:43.820264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efd35b86b916'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('banks')
    op.drop_table('account_remembers')
    op.drop_table('saving_accounts')
    op.drop_table('debt_reminders')
    op.drop_table('user_accounts')
    op.drop_table('payment_accounts')
    op.drop_table('customers')
    op.drop_table('bank_transfers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transfers',
    sa.Column('BankTransferId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CustomerId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('Content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('Method', mysql.BIT(length=10), nullable=False, comment='0: người nhận trả phí  /  1:người gửi trả ph'),
    sa.Column('CreatedDate', mysql.DATETIME(), nullable=False),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('BankTransferId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('CustomerId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CustomerName', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('CreatedDate', mysql.DATETIME(), nullable=False),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UserAccountId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PaymentAccountId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SavingAccountId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('CustomerId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment_accounts',
    sa.Column('PaymentAccountId', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_vietnamese_ci', length=50), nullable=False),
    sa.Column('ExcessAmount', mysql.DECIMAL(precision=10, scale=0), nullable=False, comment='Số dư'),
    sa.PrimaryKeyConstraint('PaymentAccountId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_accounts',
    sa.Column('AccountId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserName', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_vietnamese_ci', length=50), nullable=False),
    sa.Column('Password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_vietnamese_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('AccountId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('debt_reminders',
    sa.Column('DebtReminderId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('Content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('CreatedDate', mysql.DATETIME(), nullable=False),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CustomerId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Status', mysql.BIT(length=10), nullable=False),
    sa.PrimaryKeyConstraint('DebtReminderId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('saving_accounts',
    sa.Column('SavingAcountId', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_vietnamese_ci', length=50), nullable=False),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account_remembers',
    sa.Column('AccountRememberId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CustomerId', mysql.INTEGER(), autoincrement=False, nullable=False, comment='mã chủ tài khoản'),
    sa.Column('CustomerRememberId', mysql.INTEGER(), autoincrement=False, nullable=False, comment='mã tài khoản nhớ tên'),
    sa.Column('RememberName', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_vietnamese_ci'), nullable=False, comment='tên gợi ý'),
    sa.Column('CreatedDate', mysql.DATETIME(), nullable=False),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('AccountRememberId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('banks',
    sa.Column('BankId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BankName', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('CreatedDate', mysql.DATETIME(), nullable=False),
    sa.Column('CreateBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('BankId'),
    mysql_collate='utf8mb4_vietnamese_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
