"""create table payment account

Revision ID: f3a355cd545e
Revises: c9e7d240f360
Create Date: 2020-02-22 21:35:36.443024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a355cd545e'
down_revision = 'c9e7d240f360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_account',
    sa.Column('PaymentAccountId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NumberPaymentAccount', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PaymentAccountId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_account')
    # ### end Alembic commands ###
